name: flutterprovider
description: "Flutter Provider is a faster UI development kit"
version: 0.0.1
homepage: https://github.com/flutterprovider/flutterprovider
repository: https://github.com/flutterprovider/flutterprovider.git
issue_tracker: https://github.com/flutterprovider/flutterprovider/issues

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
# --------------------------
#  audioplayers: ^6.5.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
#  cloud_firestore: ^6.0.0
  cupertino_icons: ^1.0.8
#  geolocator: ^14.0.0
  google_fonts: ^6.3.2
#  http: ^1.3.0
#  hive_flutter: ^1.1.0
#  intl: ^0.18.1
#  firebase_auth: ^6.0.0
#  firebase_core: ^4.0.0
#  flutter_cache_manager: ^3.3.0
#  flutter_contacts: ^1.1.7
#  flutter_launcher_icons: ^0.14.4
#  flutter_native_splash: ^2.4.6
#  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.2.1
#  package_info_plus: ^8.3.0
#  path_provider: ^2.1.5
#  permission_handler: ^11.3.1
#  provider: ^6.1.5
#  lottie: ^3.3.1
#  refresh_loadmore: ^2.0.7
#  share_plus: ^7.2.1
#  shared_preferences: ^2.5.3
#  url_launcher: ^6.3.2
#  vibration: ^3.1.3
#  video_player: ^2.9.5
# ------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
# if folder is empty it will not push to GitHub. comment it or add .gitkeep file in empty folder
  assets:
    - assets/
    - assets/audios/
    - assets/gifs/
    - assets/icons/
    - assets/images/
    - assets/jsons/
    - assets/lottiefiles/
    - assets/scripts/
    - assets/texts/
    - assets/videos/

topics:
  - class
  - widget
  - animation
  - extension


screenshots:
  - path: screenshots/flutterprovider.png
    description: "Package icon"
  # - path: screenshots/button_pressed.png
  #   description: "Button pressed animation"

# funding:
#   - https://github.com/sponsors/yourusername

platforms:
  android:
  ios:
  web:
  macos:
  windows:
  linux:

license: MIT

